config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "flights#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :flights, only: [:index]

  resources :bookings, only: [:new, :create, :show]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: :departure_airport_id, class_name: "Flight"
  has_many :arriving_flights, foreign_key: :arrival_airport_id, class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :arrival_airport, class_name: "Airport"
  belongs_to :departure_airport, class_name: "Airport"
  has_many :bookings

  scope :departing_from, -> (departure_id) { where(departure_airport_id: departure_id) }
  scope :arriving_at, -> (arrival_id) { where(arrival_airport_id: arrival_id)}
  scope :departing_on, -> (date) { where(start_time: date) }
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :require_passengers, only: [:new, :create]

  def new
    @flight = Flight.find(params[:flight_id])
    @booking = Booking.new
    @num_passengers = params[:num_passengers].to_i
    # These are associated with our booking hence rails knows to load them
    @num_passengers.times {@booking.passengers.build}
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer.with(passenger: passenger).confirmation_booking.deliver_now
      end
      redirect_to @booking
    else
      render :new, status: :unprocessable_entity
    end

  end

  def show
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
    @passengers = @booking.passengers
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end

  def require_passengers
    if params[:num_passengers] == '0'
      flash[:notice] = "Please choose a number of Passengers and press save"
      redirect_to root_path
    end
  end


end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @departing_flights = Airport.joins(:departing_flights).distinct.map { |air_port| [air_port.code, air_port.id]}
    @dates = Flight.distinct.pluck(:start_time).map { |d| [d.strftime("%m/%d/%Y"), d] }
    @arriving_flights = Airport.joins(:arriving_flights).distinct.map { |air_port| [air_port.code, air_port.id]}

    select_flights
  end

  private

  def select_flights
    if params[:departure_airport_id] == '0' && params[:start_time] == '0' && params[:arrival_airport_id] == '0'
      @flights = []
      return
    end
    # Will filter out flights based on search results
    @flights = Flight
    @flights = @flights.departing_from(params[:departure_airport_id].to_i) unless params[:departure_airport_id] == '0'
    @flights = @flights.departing_on(params[:start_time]) unless params[:start_time] == '0'
    @flights = @flights.arriving_at(params[:arrival_airport_id].to_i) unless params[:arrival_airport_id] == '0'

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Book your flight</h1>

<h2> Flight: <%= @flight.departure_airport.code %> ----> <%= @flight.arrival_airport.code %></h2>
<h2><%= @flight.start_time %></h2>

<%= form_with model: @booking do |f|%>
  <%= f.hidden_field :flight_id, value: params[:flight_id] %>

  <div data-controller="passengers"  data-passengers-num-passengers-value=<%= params[:num_passengers] %>>

    <template data-passengers-target="template">
      <div><h3>Passenger</h3>
        <div>
          <label for="booking_passengers_attributes_[new]_name">Name</label>
          <input type="text" name="booking[passengers_attributes][new][name]" id="booking_passengers_attributes_new_name">
        </div>

        <div>
          <label for="booking_passengers_attributes_new_email">Email</label>
          <input type="email" name="booking[passengers_attributes][new][email]" id="booking_passengers_attributes_new_email">
        </div>
      </div>
    </template>
    <div data-passengers-target="container">
      <%= f.fields_for :passengers do |passenger_form, i| %>
        <div>
          <h3>Passenger</h3>
          <div>
            <%= passenger_form.label :name %>
            <%= passenger_form.text_field :name %>
          </div>

          <div>
            <%= passenger_form.label :email %>
            <%= passenger_form.email_field :email %>
          </div>
        </div>
      <% end %>
    </div>
    <button data-passengers-target="removebtn" data-action="click->passengers#remove" type="button">Remove</button>
    <button type="button" data-action="click->passengers#add">Add Passenger</button>
  </div>

  <%= f.submit %>

<% end %>

app/views/bookings/show.html.erb
<h1>Your Flight</h1>
<h2>From: <%= @flight.departure_airport.code %> </h2>
<h2>To: <%= @flight.arrival_airport.code %></h2>
<h3>Date: <%= @flight.start_time %></h3>
<h3>Duration: <%= @flight.flight_duration %> hours </h3>

<h2>Passengers</h2>
<ul>
  <% @passengers.each do |passenger|%>
  <li>
    <%= passenger.name %> <br>
    <%= passenger.email %>
  </li>
  <% end %>
</ul>

app/views/flights/index.html.erb
<h1>Select Your Flight</h1>

<%= form_with url: flights_path, method: :get, local: true do |f|  %>
  <div>
    <%= f.label :departure_airport_id, "Departure Airports" %>
    <%= f.select(:departure_airport_id, options_for_select(@departing_flights + [["Select", 0]], params[:departure_airport_id] || 0)) %>
  </div>

  <div>
    <%= f.label :start_time, "Flight Date" %>
    <%= f.select(:start_time, options_for_select(@dates + [["Select", 0]], params[:start_time] || 0)) %>
  </div>

  <div>
    <%= f.label :arrival_airport_id, "Arrival Aiports" %>
    <%= f.select(:arrival_airport_id, options_for_select(@arriving_flights + [["Select", 0]], params[:arrival_airport_id] || 0)) %>
  </div>

  <div>
    <%= f.label :num_passengers, "Number of Passengers" %>
    <%= f.select(:num_passengers, options_for_select(Array.new(4) { |i| i + 1} + [["Select", 0]], params[:num_passengers] || 0 )) %>
  </div>
  <%= f.submit %>
<% end %>

<% unless @flights.empty? %>
  <%= form_with url: new_booking_path, method: :get, local: true do |f| %>
    <%= f.hidden_field :num_passengers, value: params[:num_passengers] %>

    <%= f.collection_radio_buttons :flight_id, @flights, :id, :start_time do |b| %>
      <div>
        <%= b.radio_button %>
        <%= b.label do %>
          <%= b.object.departure_airport.code %> - <%= b.object.arrival_airport.code %> <br>
          Date: <%= b.object.start_time %>
        <% end %>
      </div>
    <% end %>

    <%= f.submit "Select Flight" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |key, message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>